hostname = 

            # > CamScanner < #
            ap*.intsig.net              ,
            
            # > 百度网盘部分 < #
            pan.baidu.com               ,
            
            # > 西  窗  烛 < #
            avoscloud.com               ,
            
            # > WPS  部分 < #
            account.wps.cn              ,
            vira.llsapp.com             ,
            notability.com              ,
            server.yoyiapp.com          ,
            *.gotokeep.com              ,
            buy.itunes.apple.com        ,
            api.revenuecat.com          ,
            dxy.com                     ,
            mid.zineapi.com             ,
            api-prod.languagedrops.com  ,
            *.wallpaperscraft.com       ,
            vni.kwaiying.com            ,
            spclient.wg.spotify.com
